

module.exports = {
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  RECEIVED_PROFILE: 'RECEIVED_PROFILE',
  RECEIVED_APPS: 'RECEIVED_APPS',
  RECEIVED_USERS: 'RECEIVED_USERS',
  RECEIVED_ROLES: 'RECEIVED_ROLES',
  SAVED_APP: 'SAVED_APP',
  SAVED_USER: 'SAVED_USER',
  //SAVED_ROLE: 'SAVED_ROLE',
  DELETED_ROLE: 'DELETED_ROLE'
};
