

module.exports = {
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  RECEIVED_PROFILE: 'RECEIVED_PROFILE',
  RECEIVED_APPS: 'RECEIVED_APPS',
  RECEIVED_USERS: 'RECEIVED_USERS',
  PAGE_TITLE_SET: 'PAGE_TITLE_SET',
  RECEIVED_ROLES: 'RECEIVED_ROLES'
}
